// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pbrebuilder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// empty message
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// message that only contains a value of bool
type BoolMessage struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolMessage) Reset()         { *m = BoolMessage{} }
func (m *BoolMessage) String() string { return proto.CompactTextString(m) }
func (*BoolMessage) ProtoMessage()    {}
func (*BoolMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *BoolMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolMessage.Unmarshal(m, b)
}
func (m *BoolMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolMessage.Marshal(b, m, deterministic)
}
func (m *BoolMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolMessage.Merge(m, src)
}
func (m *BoolMessage) XXX_Size() int {
	return xxx_messageInfo_BoolMessage.Size(m)
}
func (m *BoolMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BoolMessage proto.InternalMessageInfo

func (m *BoolMessage) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

// message that only contains a value of string
type StringMsg struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMsg) Reset()         { *m = StringMsg{} }
func (m *StringMsg) String() string { return proto.CompactTextString(m) }
func (*StringMsg) ProtoMessage()    {}
func (*StringMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *StringMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMsg.Unmarshal(m, b)
}
func (m *StringMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMsg.Marshal(b, m, deterministic)
}
func (m *StringMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMsg.Merge(m, src)
}
func (m *StringMsg) XXX_Size() int {
	return xxx_messageInfo_StringMsg.Size(m)
}
func (m *StringMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StringMsg proto.InternalMessageInfo

func (m *StringMsg) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// message that only contains two values of string
type String2Msg struct {
	Param1               string   `protobuf:"bytes,1,opt,name=param1,proto3" json:"param1,omitempty"`
	Param2               string   `protobuf:"bytes,2,opt,name=param2,proto3" json:"param2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String2Msg) Reset()         { *m = String2Msg{} }
func (m *String2Msg) String() string { return proto.CompactTextString(m) }
func (*String2Msg) ProtoMessage()    {}
func (*String2Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *String2Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String2Msg.Unmarshal(m, b)
}
func (m *String2Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String2Msg.Marshal(b, m, deterministic)
}
func (m *String2Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String2Msg.Merge(m, src)
}
func (m *String2Msg) XXX_Size() int {
	return xxx_messageInfo_String2Msg.Size(m)
}
func (m *String2Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_String2Msg.DiscardUnknown(m)
}

var xxx_messageInfo_String2Msg proto.InternalMessageInfo

func (m *String2Msg) GetParam1() string {
	if m != nil {
		return m.Param1
	}
	return ""
}

func (m *String2Msg) GetParam2() string {
	if m != nil {
		return m.Param2
	}
	return ""
}

// message that only contains a value of int32
type Int32Msg struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Msg) Reset()         { *m = Int32Msg{} }
func (m *Int32Msg) String() string { return proto.CompactTextString(m) }
func (*Int32Msg) ProtoMessage()    {}
func (*Int32Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *Int32Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Msg.Unmarshal(m, b)
}
func (m *Int32Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Msg.Marshal(b, m, deterministic)
}
func (m *Int32Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Msg.Merge(m, src)
}
func (m *Int32Msg) XXX_Size() int {
	return xxx_messageInfo_Int32Msg.Size(m)
}
func (m *Int32Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Msg proto.InternalMessageInfo

func (m *Int32Msg) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// message that only contains a value of int64
type Int64Msg struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Msg) Reset()         { *m = Int64Msg{} }
func (m *Int64Msg) String() string { return proto.CompactTextString(m) }
func (*Int64Msg) ProtoMessage()    {}
func (*Int64Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *Int64Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Msg.Unmarshal(m, b)
}
func (m *Int64Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Msg.Marshal(b, m, deterministic)
}
func (m *Int64Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Msg.Merge(m, src)
}
func (m *Int64Msg) XXX_Size() int {
	return xxx_messageInfo_Int64Msg.Size(m)
}
func (m *Int64Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Msg proto.InternalMessageInfo

func (m *Int64Msg) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Node message
type NodeMsg struct {
	ID                   int32            `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string           `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PubKey               string           `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Owner                string           `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	ProfitAcc            string           `protobuf:"bytes,5,opt,name=profitAcc,proto3" json:"profitAcc,omitempty"`
	PoolID               string           `protobuf:"bytes,6,opt,name=poolID,proto3" json:"poolID,omitempty"`
	PoolOwner            string           `protobuf:"bytes,7,opt,name=poolOwner,proto3" json:"poolOwner,omitempty"`
	Quota                int64            `protobuf:"varint,8,opt,name=quota,proto3" json:"quota,omitempty"`
	Addrs                []string         `protobuf:"bytes,9,rep,name=addrs,proto3" json:"addrs,omitempty"`
	CPU                  int32            `protobuf:"varint,10,opt,name=cPU,proto3" json:"cPU,omitempty"`
	Memory               int32            `protobuf:"varint,11,opt,name=memory,proto3" json:"memory,omitempty"`
	Bandwidth            int32            `protobuf:"varint,12,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	MaxDataSpace         int64            `protobuf:"varint,13,opt,name=maxDataSpace,proto3" json:"maxDataSpace,omitempty"`
	AssignedSpace        int64            `protobuf:"varint,14,opt,name=assignedSpace,proto3" json:"assignedSpace,omitempty"`
	ProductiveSpace      int64            `protobuf:"varint,15,opt,name=productiveSpace,proto3" json:"productiveSpace,omitempty"`
	UsedSpace            int64            `protobuf:"varint,16,opt,name=usedSpace,proto3" json:"usedSpace,omitempty"`
	Weight               float64          `protobuf:"fixed64,17,opt,name=weight,proto3" json:"weight,omitempty"`
	Valid                int32            `protobuf:"varint,18,opt,name=valid,proto3" json:"valid,omitempty"`
	Relay                int32            `protobuf:"varint,19,opt,name=relay,proto3" json:"relay,omitempty"`
	Status               int32            `protobuf:"varint,20,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            int64            `protobuf:"varint,21,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              int32            `protobuf:"varint,22,opt,name=version,proto3" json:"version,omitempty"`
	Rebuilding           int32            `protobuf:"varint,23,opt,name=rebuilding,proto3" json:"rebuilding,omitempty"`
	RealSpace            int64            `protobuf:"varint,24,opt,name=realSpace,proto3" json:"realSpace,omitempty"`
	Tx                   int64            `protobuf:"varint,25,opt,name=tx,proto3" json:"tx,omitempty"`
	Rx                   int64            `protobuf:"varint,26,opt,name=rx,proto3" json:"rx,omitempty"`
	Ext                  string           `protobuf:"bytes,27,opt,name=ext,proto3" json:"ext,omitempty"`
	Uspaces              map[string]int64 `protobuf:"bytes,28,rep,name=uspaces,proto3" json:"uspaces,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NodeMsg) Reset()         { *m = NodeMsg{} }
func (m *NodeMsg) String() string { return proto.CompactTextString(m) }
func (*NodeMsg) ProtoMessage()    {}
func (*NodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *NodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMsg.Unmarshal(m, b)
}
func (m *NodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMsg.Marshal(b, m, deterministic)
}
func (m *NodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMsg.Merge(m, src)
}
func (m *NodeMsg) XXX_Size() int {
	return xxx_messageInfo_NodeMsg.Size(m)
}
func (m *NodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMsg proto.InternalMessageInfo

func (m *NodeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NodeMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *NodeMsg) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *NodeMsg) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NodeMsg) GetProfitAcc() string {
	if m != nil {
		return m.ProfitAcc
	}
	return ""
}

func (m *NodeMsg) GetPoolID() string {
	if m != nil {
		return m.PoolID
	}
	return ""
}

func (m *NodeMsg) GetPoolOwner() string {
	if m != nil {
		return m.PoolOwner
	}
	return ""
}

func (m *NodeMsg) GetQuota() int64 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *NodeMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *NodeMsg) GetCPU() int32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *NodeMsg) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *NodeMsg) GetBandwidth() int32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *NodeMsg) GetMaxDataSpace() int64 {
	if m != nil {
		return m.MaxDataSpace
	}
	return 0
}

func (m *NodeMsg) GetAssignedSpace() int64 {
	if m != nil {
		return m.AssignedSpace
	}
	return 0
}

func (m *NodeMsg) GetProductiveSpace() int64 {
	if m != nil {
		return m.ProductiveSpace
	}
	return 0
}

func (m *NodeMsg) GetUsedSpace() int64 {
	if m != nil {
		return m.UsedSpace
	}
	return 0
}

func (m *NodeMsg) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *NodeMsg) GetValid() int32 {
	if m != nil {
		return m.Valid
	}
	return 0
}

func (m *NodeMsg) GetRelay() int32 {
	if m != nil {
		return m.Relay
	}
	return 0
}

func (m *NodeMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *NodeMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NodeMsg) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *NodeMsg) GetRebuilding() int32 {
	if m != nil {
		return m.Rebuilding
	}
	return 0
}

func (m *NodeMsg) GetRealSpace() int64 {
	if m != nil {
		return m.RealSpace
	}
	return 0
}

func (m *NodeMsg) GetTx() int64 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *NodeMsg) GetRx() int64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *NodeMsg) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *NodeMsg) GetUspaces() map[string]int64 {
	if m != nil {
		return m.Uspaces
	}
	return nil
}

// SuperNode message
type SuperNodeMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	PubKey               string   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	PrivKey              string   `protobuf:"bytes,4,opt,name=privKey,proto3" json:"privKey,omitempty"`
	Addrs                []string `protobuf:"bytes,5,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuperNodeMsg) Reset()         { *m = SuperNodeMsg{} }
func (m *SuperNodeMsg) String() string { return proto.CompactTextString(m) }
func (*SuperNodeMsg) ProtoMessage()    {}
func (*SuperNodeMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *SuperNodeMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperNodeMsg.Unmarshal(m, b)
}
func (m *SuperNodeMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperNodeMsg.Marshal(b, m, deterministic)
}
func (m *SuperNodeMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperNodeMsg.Merge(m, src)
}
func (m *SuperNodeMsg) XXX_Size() int {
	return xxx_messageInfo_SuperNodeMsg.Size(m)
}
func (m *SuperNodeMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperNodeMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SuperNodeMsg proto.InternalMessageInfo

func (m *SuperNodeMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SuperNodeMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SuperNodeMsg) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *SuperNodeMsg) GetPrivKey() string {
	if m != nil {
		return m.PrivKey
	}
	return ""
}

func (m *SuperNodeMsg) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

// NodeStat message
type NodeStatMsg struct {
	ActiveMiners         int64    `protobuf:"varint,1,opt,name=activeMiners,proto3" json:"activeMiners,omitempty"`
	TotalMiners          int64    `protobuf:"varint,2,opt,name=totalMiners,proto3" json:"totalMiners,omitempty"`
	MaxTotal             int64    `protobuf:"varint,3,opt,name=maxTotal,proto3" json:"maxTotal,omitempty"`
	AssignedTotal        int64    `protobuf:"varint,4,opt,name=assignedTotal,proto3" json:"assignedTotal,omitempty"`
	ProductiveTotal      int64    `protobuf:"varint,5,opt,name=productiveTotal,proto3" json:"productiveTotal,omitempty"`
	UsedTotal            int64    `protobuf:"varint,6,opt,name=usedTotal,proto3" json:"usedTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStatMsg) Reset()         { *m = NodeStatMsg{} }
func (m *NodeStatMsg) String() string { return proto.CompactTextString(m) }
func (*NodeStatMsg) ProtoMessage()    {}
func (*NodeStatMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *NodeStatMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatMsg.Unmarshal(m, b)
}
func (m *NodeStatMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatMsg.Marshal(b, m, deterministic)
}
func (m *NodeStatMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatMsg.Merge(m, src)
}
func (m *NodeStatMsg) XXX_Size() int {
	return xxx_messageInfo_NodeStatMsg.Size(m)
}
func (m *NodeStatMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatMsg.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatMsg proto.InternalMessageInfo

func (m *NodeStatMsg) GetActiveMiners() int64 {
	if m != nil {
		return m.ActiveMiners
	}
	return 0
}

func (m *NodeStatMsg) GetTotalMiners() int64 {
	if m != nil {
		return m.TotalMiners
	}
	return 0
}

func (m *NodeStatMsg) GetMaxTotal() int64 {
	if m != nil {
		return m.MaxTotal
	}
	return 0
}

func (m *NodeStatMsg) GetAssignedTotal() int64 {
	if m != nil {
		return m.AssignedTotal
	}
	return 0
}

func (m *NodeStatMsg) GetProductiveTotal() int64 {
	if m != nil {
		return m.ProductiveTotal
	}
	return 0
}

func (m *NodeStatMsg) GetUsedTotal() int64 {
	if m != nil {
		return m.UsedTotal
	}
	return 0
}

// SpotCheckTask message
type SpotCheckTaskMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr                 string   `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	VNI                  string   `protobuf:"bytes,4,opt,name=vNI,proto3" json:"vNI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpotCheckTaskMsg) Reset()         { *m = SpotCheckTaskMsg{} }
func (m *SpotCheckTaskMsg) String() string { return proto.CompactTextString(m) }
func (*SpotCheckTaskMsg) ProtoMessage()    {}
func (*SpotCheckTaskMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *SpotCheckTaskMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckTaskMsg.Unmarshal(m, b)
}
func (m *SpotCheckTaskMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckTaskMsg.Marshal(b, m, deterministic)
}
func (m *SpotCheckTaskMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckTaskMsg.Merge(m, src)
}
func (m *SpotCheckTaskMsg) XXX_Size() int {
	return xxx_messageInfo_SpotCheckTaskMsg.Size(m)
}
func (m *SpotCheckTaskMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckTaskMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckTaskMsg proto.InternalMessageInfo

func (m *SpotCheckTaskMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *SpotCheckTaskMsg) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *SpotCheckTaskMsg) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *SpotCheckTaskMsg) GetVNI() string {
	if m != nil {
		return m.VNI
	}
	return ""
}

// SpotCheckList message
type SpotCheckListMsg struct {
	TaskID               string              `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	TaskList             []*SpotCheckTaskMsg `protobuf:"bytes,2,rep,name=taskList,proto3" json:"taskList,omitempty"`
	Timestamp            int64               `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SpotCheckListMsg) Reset()         { *m = SpotCheckListMsg{} }
func (m *SpotCheckListMsg) String() string { return proto.CompactTextString(m) }
func (*SpotCheckListMsg) ProtoMessage()    {}
func (*SpotCheckListMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *SpotCheckListMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpotCheckListMsg.Unmarshal(m, b)
}
func (m *SpotCheckListMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpotCheckListMsg.Marshal(b, m, deterministic)
}
func (m *SpotCheckListMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotCheckListMsg.Merge(m, src)
}
func (m *SpotCheckListMsg) XXX_Size() int {
	return xxx_messageInfo_SpotCheckListMsg.Size(m)
}
func (m *SpotCheckListMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotCheckListMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SpotCheckListMsg proto.InternalMessageInfo

func (m *SpotCheckListMsg) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *SpotCheckListMsg) GetTaskList() []*SpotCheckTaskMsg {
	if m != nil {
		return m.TaskList
	}
	return nil
}

func (m *SpotCheckListMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// response message of GetSpotCheckList function
type GetSpotCheckListResp struct {
	SpotCheckLists       []*SpotCheckListMsg `protobuf:"bytes,1,rep,name=spotCheckLists,proto3" json:"spotCheckLists,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetSpotCheckListResp) Reset()         { *m = GetSpotCheckListResp{} }
func (m *GetSpotCheckListResp) String() string { return proto.CompactTextString(m) }
func (*GetSpotCheckListResp) ProtoMessage()    {}
func (*GetSpotCheckListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *GetSpotCheckListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSpotCheckListResp.Unmarshal(m, b)
}
func (m *GetSpotCheckListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSpotCheckListResp.Marshal(b, m, deterministic)
}
func (m *GetSpotCheckListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSpotCheckListResp.Merge(m, src)
}
func (m *GetSpotCheckListResp) XXX_Size() int {
	return xxx_messageInfo_GetSpotCheckListResp.Size(m)
}
func (m *GetSpotCheckListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSpotCheckListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSpotCheckListResp proto.InternalMessageInfo

func (m *GetSpotCheckListResp) GetSpotCheckLists() []*SpotCheckListMsg {
	if m != nil {
		return m.SpotCheckLists
	}
	return nil
}

// response message with multiple nodes
type NodesResp struct {
	Nodes                []*NodeMsg `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NodesResp) Reset()         { *m = NodesResp{} }
func (m *NodesResp) String() string { return proto.CompactTextString(m) }
func (*NodesResp) ProtoMessage()    {}
func (*NodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *NodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodesResp.Unmarshal(m, b)
}
func (m *NodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodesResp.Marshal(b, m, deterministic)
}
func (m *NodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodesResp.Merge(m, src)
}
func (m *NodesResp) XXX_Size() int {
	return xxx_messageInfo_NodesResp.Size(m)
}
func (m *NodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_NodesResp proto.InternalMessageInfo

func (m *NodesResp) GetNodes() []*NodeMsg {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// response message with multiple supernodes
type SuperNodesResp struct {
	SuperNodes           []*SuperNodeMsg `protobuf:"bytes,1,rep,name=superNodes,proto3" json:"superNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SuperNodesResp) Reset()         { *m = SuperNodesResp{} }
func (m *SuperNodesResp) String() string { return proto.CompactTextString(m) }
func (*SuperNodesResp) ProtoMessage()    {}
func (*SuperNodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *SuperNodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuperNodesResp.Unmarshal(m, b)
}
func (m *SuperNodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuperNodesResp.Marshal(b, m, deterministic)
}
func (m *SuperNodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuperNodesResp.Merge(m, src)
}
func (m *SuperNodesResp) XXX_Size() int {
	return xxx_messageInfo_SuperNodesResp.Size(m)
}
func (m *SuperNodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SuperNodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_SuperNodesResp proto.InternalMessageInfo

func (m *SuperNodesResp) GetSuperNodes() []*SuperNodeMsg {
	if m != nil {
		return m.SuperNodes
	}
	return nil
}

// request message of IncrUsedSpace function
type IncrUsedSpaceReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Incr                 int64    `protobuf:"varint,2,opt,name=incr,proto3" json:"incr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrUsedSpaceReq) Reset()         { *m = IncrUsedSpaceReq{} }
func (m *IncrUsedSpaceReq) String() string { return proto.CompactTextString(m) }
func (*IncrUsedSpaceReq) ProtoMessage()    {}
func (*IncrUsedSpaceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *IncrUsedSpaceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrUsedSpaceReq.Unmarshal(m, b)
}
func (m *IncrUsedSpaceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrUsedSpaceReq.Marshal(b, m, deterministic)
}
func (m *IncrUsedSpaceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrUsedSpaceReq.Merge(m, src)
}
func (m *IncrUsedSpaceReq) XXX_Size() int {
	return xxx_messageInfo_IncrUsedSpaceReq.Size(m)
}
func (m *IncrUsedSpaceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrUsedSpaceReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncrUsedSpaceReq proto.InternalMessageInfo

func (m *IncrUsedSpaceReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *IncrUsedSpaceReq) GetIncr() int64 {
	if m != nil {
		return m.Incr
	}
	return 0
}

// request message of AllocNodes function
type AllocNodesReq struct {
	ShardCount           int32    `protobuf:"varint,1,opt,name=shardCount,proto3" json:"shardCount,omitempty"`
	ErrIDs               []int32  `protobuf:"varint,2,rep,packed,name=errIDs,proto3" json:"errIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllocNodesReq) Reset()         { *m = AllocNodesReq{} }
func (m *AllocNodesReq) String() string { return proto.CompactTextString(m) }
func (*AllocNodesReq) ProtoMessage()    {}
func (*AllocNodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *AllocNodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllocNodesReq.Unmarshal(m, b)
}
func (m *AllocNodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllocNodesReq.Marshal(b, m, deterministic)
}
func (m *AllocNodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllocNodesReq.Merge(m, src)
}
func (m *AllocNodesReq) XXX_Size() int {
	return xxx_messageInfo_AllocNodesReq.Size(m)
}
func (m *AllocNodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AllocNodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_AllocNodesReq proto.InternalMessageInfo

func (m *AllocNodesReq) GetShardCount() int32 {
	if m != nil {
		return m.ShardCount
	}
	return 0
}

func (m *AllocNodesReq) GetErrIDs() []int32 {
	if m != nil {
		return m.ErrIDs
	}
	return nil
}

// request message of GetNodes function
type GetNodesReq struct {
	NodeIDs              []int32  `protobuf:"varint,1,rep,packed,name=nodeIDs,proto3" json:"nodeIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesReq) Reset()         { *m = GetNodesReq{} }
func (m *GetNodesReq) String() string { return proto.CompactTextString(m) }
func (*GetNodesReq) ProtoMessage()    {}
func (*GetNodesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *GetNodesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesReq.Unmarshal(m, b)
}
func (m *GetNodesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesReq.Marshal(b, m, deterministic)
}
func (m *GetNodesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesReq.Merge(m, src)
}
func (m *GetNodesReq) XXX_Size() int {
	return xxx_messageInfo_GetNodesReq.Size(m)
}
func (m *GetNodesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesReq proto.InternalMessageInfo

func (m *GetNodesReq) GetNodeIDs() []int32 {
	if m != nil {
		return m.NodeIDs
	}
	return nil
}

// request message of AddDNI function
type DNIReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Shard                []byte   `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNIReq) Reset()         { *m = DNIReq{} }
func (m *DNIReq) String() string { return proto.CompactTextString(m) }
func (*DNIReq) ProtoMessage()    {}
func (*DNIReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *DNIReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNIReq.Unmarshal(m, b)
}
func (m *DNIReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNIReq.Marshal(b, m, deterministic)
}
func (m *DNIReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNIReq.Merge(m, src)
}
func (m *DNIReq) XXX_Size() int {
	return xxx_messageInfo_DNIReq.Size(m)
}
func (m *DNIReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DNIReq.DiscardUnknown(m)
}

var xxx_messageInfo_DNIReq proto.InternalMessageInfo

func (m *DNIReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DNIReq) GetShard() []byte {
	if m != nil {
		return m.Shard
	}
	return nil
}

// request message of UpdateTaskStatus function
type UpdateTaskStatusReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvalidNode          int32    `protobuf:"varint,2,opt,name=invalidNode,proto3" json:"invalidNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskStatusReq) Reset()         { *m = UpdateTaskStatusReq{} }
func (m *UpdateTaskStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskStatusReq) ProtoMessage()    {}
func (*UpdateTaskStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *UpdateTaskStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskStatusReq.Unmarshal(m, b)
}
func (m *UpdateTaskStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateTaskStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskStatusReq.Merge(m, src)
}
func (m *UpdateTaskStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskStatusReq.Size(m)
}
func (m *UpdateTaskStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskStatusReq proto.InternalMessageInfo

func (m *UpdateTaskStatusReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateTaskStatusReq) GetInvalidNode() int32 {
	if m != nil {
		return m.InvalidNode
	}
	return 0
}

// ShardCount message
type ShardCountMsg struct {
	ID                   int32    `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`
	Cnt                  int64    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardCountMsg) Reset()         { *m = ShardCountMsg{} }
func (m *ShardCountMsg) String() string { return proto.CompactTextString(m) }
func (*ShardCountMsg) ProtoMessage()    {}
func (*ShardCountMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *ShardCountMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardCountMsg.Unmarshal(m, b)
}
func (m *ShardCountMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardCountMsg.Marshal(b, m, deterministic)
}
func (m *ShardCountMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardCountMsg.Merge(m, src)
}
func (m *ShardCountMsg) XXX_Size() int {
	return xxx_messageInfo_ShardCountMsg.Size(m)
}
func (m *ShardCountMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardCountMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ShardCountMsg proto.InternalMessageInfo

func (m *ShardCountMsg) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShardCountMsg) GetCnt() int64 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

// request message of GetInvalidNodes function
type GetInvalidNodesResp struct {
	ShardCounts          []*ShardCountMsg `protobuf:"bytes,1,rep,name=shardCounts,proto3" json:"shardCounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInvalidNodesResp) Reset()         { *m = GetInvalidNodesResp{} }
func (m *GetInvalidNodesResp) String() string { return proto.CompactTextString(m) }
func (*GetInvalidNodesResp) ProtoMessage()    {}
func (*GetInvalidNodesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *GetInvalidNodesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInvalidNodesResp.Unmarshal(m, b)
}
func (m *GetInvalidNodesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInvalidNodesResp.Marshal(b, m, deterministic)
}
func (m *GetInvalidNodesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInvalidNodesResp.Merge(m, src)
}
func (m *GetInvalidNodesResp) XXX_Size() int {
	return xxx_messageInfo_GetInvalidNodesResp.Size(m)
}
func (m *GetInvalidNodesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInvalidNodesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInvalidNodesResp proto.InternalMessageInfo

func (m *GetInvalidNodesResp) GetShardCounts() []*ShardCountMsg {
	if m != nil {
		return m.ShardCounts
	}
	return nil
}

// request message of GetInvalidNodes function
type GetRebuildItemReq struct {
	MinerID              int32    `protobuf:"varint,1,opt,name=minerID,proto3" json:"minerID,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRebuildItemReq) Reset()         { *m = GetRebuildItemReq{} }
func (m *GetRebuildItemReq) String() string { return proto.CompactTextString(m) }
func (*GetRebuildItemReq) ProtoMessage()    {}
func (*GetRebuildItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *GetRebuildItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRebuildItemReq.Unmarshal(m, b)
}
func (m *GetRebuildItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRebuildItemReq.Marshal(b, m, deterministic)
}
func (m *GetRebuildItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRebuildItemReq.Merge(m, src)
}
func (m *GetRebuildItemReq) XXX_Size() int {
	return xxx_messageInfo_GetRebuildItemReq.Size(m)
}
func (m *GetRebuildItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRebuildItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRebuildItemReq proto.InternalMessageInfo

func (m *GetRebuildItemReq) GetMinerID() int32 {
	if m != nil {
		return m.MinerID
	}
	return 0
}

func (m *GetRebuildItemReq) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetRebuildItemReq) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// response message of GetInvalidNodes function
type GetRebuildItemResp struct {
	Node                 *NodeMsg `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Shards               [][]byte `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRebuildItemResp) Reset()         { *m = GetRebuildItemResp{} }
func (m *GetRebuildItemResp) String() string { return proto.CompactTextString(m) }
func (*GetRebuildItemResp) ProtoMessage()    {}
func (*GetRebuildItemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{22}
}

func (m *GetRebuildItemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRebuildItemResp.Unmarshal(m, b)
}
func (m *GetRebuildItemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRebuildItemResp.Marshal(b, m, deterministic)
}
func (m *GetRebuildItemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRebuildItemResp.Merge(m, src)
}
func (m *GetRebuildItemResp) XXX_Size() int {
	return xxx_messageInfo_GetRebuildItemResp.Size(m)
}
func (m *GetRebuildItemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRebuildItemResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRebuildItemResp proto.InternalMessageInfo

func (m *GetRebuildItemResp) GetNode() *NodeMsg {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GetRebuildItemResp) GetShards() [][]byte {
	if m != nil {
		return m.Shards
	}
	return nil
}

type DownloadShardRequest struct {
	VHF                  []byte   `protobuf:"bytes,1,opt,name=VHF,proto3" json:"VHF,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardRequest) Reset()         { *m = DownloadShardRequest{} }
func (m *DownloadShardRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadShardRequest) ProtoMessage()    {}
func (*DownloadShardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{23}
}

func (m *DownloadShardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardRequest.Unmarshal(m, b)
}
func (m *DownloadShardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardRequest.Marshal(b, m, deterministic)
}
func (m *DownloadShardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardRequest.Merge(m, src)
}
func (m *DownloadShardRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadShardRequest.Size(m)
}
func (m *DownloadShardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardRequest proto.InternalMessageInfo

func (m *DownloadShardRequest) GetVHF() []byte {
	if m != nil {
		return m.VHF
	}
	return nil
}

type DownloadShardResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadShardResponse) Reset()         { *m = DownloadShardResponse{} }
func (m *DownloadShardResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadShardResponse) ProtoMessage()    {}
func (*DownloadShardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{24}
}

func (m *DownloadShardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadShardResponse.Unmarshal(m, b)
}
func (m *DownloadShardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadShardResponse.Marshal(b, m, deterministic)
}
func (m *DownloadShardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadShardResponse.Merge(m, src)
}
func (m *DownloadShardResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadShardResponse.Size(m)
}
func (m *DownloadShardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadShardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadShardResponse proto.InternalMessageInfo

func (m *DownloadShardResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SignMessage struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignMessage) Reset()         { *m = SignMessage{} }
func (m *SignMessage) String() string { return proto.CompactTextString(m) }
func (*SignMessage) ProtoMessage()    {}
func (*SignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{25}
}

func (m *SignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignMessage.Unmarshal(m, b)
}
func (m *SignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignMessage.Marshal(b, m, deterministic)
}
func (m *SignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignMessage.Merge(m, src)
}
func (m *SignMessage) XXX_Size() int {
	return xxx_messageInfo_SignMessage.Size(m)
}
func (m *SignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignMessage proto.InternalMessageInfo

func (m *SignMessage) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *SignMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignMessage) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type UpdateUspaceMessage struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	FromNodeID           int32    `protobuf:"varint,2,opt,name=fromNodeID,proto3" json:"fromNodeID,omitempty"`
	Uspace               int64    `protobuf:"varint,3,opt,name=uspace,proto3" json:"uspace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUspaceMessage) Reset()         { *m = UpdateUspaceMessage{} }
func (m *UpdateUspaceMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateUspaceMessage) ProtoMessage()    {}
func (*UpdateUspaceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{26}
}

func (m *UpdateUspaceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUspaceMessage.Unmarshal(m, b)
}
func (m *UpdateUspaceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUspaceMessage.Marshal(b, m, deterministic)
}
func (m *UpdateUspaceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUspaceMessage.Merge(m, src)
}
func (m *UpdateUspaceMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateUspaceMessage.Size(m)
}
func (m *UpdateUspaceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUspaceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUspaceMessage proto.InternalMessageInfo

func (m *UpdateUspaceMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *UpdateUspaceMessage) GetFromNodeID() int32 {
	if m != nil {
		return m.FromNodeID
	}
	return 0
}

func (m *UpdateUspaceMessage) GetUspace() int64 {
	if m != nil {
		return m.Uspace
	}
	return 0
}

type PunishMessage struct {
	NodeID               int32           `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Type                 int32           `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	NeedPunish           bool            `protobuf:"varint,3,opt,name=needPunish,proto3" json:"needPunish,omitempty"`
	Count                int32           `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Rule                 map[int32]int32 `protobuf:"bytes,5,rep,name=rule,proto3" json:"rule,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PunishMessage) Reset()         { *m = PunishMessage{} }
func (m *PunishMessage) String() string { return proto.CompactTextString(m) }
func (*PunishMessage) ProtoMessage()    {}
func (*PunishMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{27}
}

func (m *PunishMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PunishMessage.Unmarshal(m, b)
}
func (m *PunishMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PunishMessage.Marshal(b, m, deterministic)
}
func (m *PunishMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PunishMessage.Merge(m, src)
}
func (m *PunishMessage) XXX_Size() int {
	return xxx_messageInfo_PunishMessage.Size(m)
}
func (m *PunishMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PunishMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PunishMessage proto.InternalMessageInfo

func (m *PunishMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *PunishMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PunishMessage) GetNeedPunish() bool {
	if m != nil {
		return m.NeedPunish
	}
	return false
}

func (m *PunishMessage) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PunishMessage) GetRule() map[int32]int32 {
	if m != nil {
		return m.Rule
	}
	return nil
}

type RebuiltMessage struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebuiltMessage) Reset()         { *m = RebuiltMessage{} }
func (m *RebuiltMessage) String() string { return proto.CompactTextString(m) }
func (*RebuiltMessage) ProtoMessage()    {}
func (*RebuiltMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{28}
}

func (m *RebuiltMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebuiltMessage.Unmarshal(m, b)
}
func (m *RebuiltMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebuiltMessage.Marshal(b, m, deterministic)
}
func (m *RebuiltMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebuiltMessage.Merge(m, src)
}
func (m *RebuiltMessage) XXX_Size() int {
	return xxx_messageInfo_RebuiltMessage.Size(m)
}
func (m *RebuiltMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RebuiltMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RebuiltMessage proto.InternalMessageInfo

func (m *RebuiltMessage) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

//重建任务
//msgid=0x2cb0
type MultiTaskDescription struct {
	Tasklist             [][]byte `protobuf:"bytes,1,rep,name=tasklist,proto3" json:"tasklist,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,2,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	SrcNodeID            int32    `protobuf:"varint,3,opt,name=srcNodeID,proto3" json:"srcNodeID,omitempty"`
	ExpiredTimeGap       int32    `protobuf:"varint,4,opt,name=expiredTimeGap,proto3" json:"expiredTimeGap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTaskDescription) Reset()         { *m = MultiTaskDescription{} }
func (m *MultiTaskDescription) String() string { return proto.CompactTextString(m) }
func (*MultiTaskDescription) ProtoMessage()    {}
func (*MultiTaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{29}
}

func (m *MultiTaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTaskDescription.Unmarshal(m, b)
}
func (m *MultiTaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTaskDescription.Marshal(b, m, deterministic)
}
func (m *MultiTaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTaskDescription.Merge(m, src)
}
func (m *MultiTaskDescription) XXX_Size() int {
	return xxx_messageInfo_MultiTaskDescription.Size(m)
}
func (m *MultiTaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTaskDescription proto.InternalMessageInfo

func (m *MultiTaskDescription) GetTasklist() [][]byte {
	if m != nil {
		return m.Tasklist
	}
	return nil
}

func (m *MultiTaskDescription) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *MultiTaskDescription) GetSrcNodeID() int32 {
	if m != nil {
		return m.SrcNodeID
	}
	return 0
}

func (m *MultiTaskDescription) GetExpiredTimeGap() int32 {
	if m != nil {
		return m.ExpiredTimeGap
	}
	return 0
}

//LRC编码重建任务
//msgid=0x68b3
type TaskDescription struct {
	Id                   []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hashs                [][]byte       `protobuf:"bytes,2,rep,name=hashs,proto3" json:"hashs,omitempty"`
	Locations            []*P2PLocation `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	ParityShardCount     int32          `protobuf:"varint,4,opt,name=parityShardCount,proto3" json:"parityShardCount,omitempty"`
	RecoverId            int32          `protobuf:"varint,5,opt,name=recoverId,proto3" json:"recoverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TaskDescription) Reset()         { *m = TaskDescription{} }
func (m *TaskDescription) String() string { return proto.CompactTextString(m) }
func (*TaskDescription) ProtoMessage()    {}
func (*TaskDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{30}
}

func (m *TaskDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescription.Unmarshal(m, b)
}
func (m *TaskDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescription.Marshal(b, m, deterministic)
}
func (m *TaskDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescription.Merge(m, src)
}
func (m *TaskDescription) XXX_Size() int {
	return xxx_messageInfo_TaskDescription.Size(m)
}
func (m *TaskDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescription.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescription proto.InternalMessageInfo

func (m *TaskDescription) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TaskDescription) GetHashs() [][]byte {
	if m != nil {
		return m.Hashs
	}
	return nil
}

func (m *TaskDescription) GetLocations() []*P2PLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *TaskDescription) GetParityShardCount() int32 {
	if m != nil {
		return m.ParityShardCount
	}
	return 0
}

func (m *TaskDescription) GetRecoverId() int32 {
	if m != nil {
		return m.RecoverId
	}
	return 0
}

//副本集编码重建任务
//msgid=0xc258
type TaskDescriptionCP struct {
	Id                   []byte         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataHash             []byte         `protobuf:"bytes,2,opt,name=dataHash,proto3" json:"dataHash,omitempty"`
	Locations            []*P2PLocation `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TaskDescriptionCP) Reset()         { *m = TaskDescriptionCP{} }
func (m *TaskDescriptionCP) String() string { return proto.CompactTextString(m) }
func (*TaskDescriptionCP) ProtoMessage()    {}
func (*TaskDescriptionCP) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{31}
}

func (m *TaskDescriptionCP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDescriptionCP.Unmarshal(m, b)
}
func (m *TaskDescriptionCP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDescriptionCP.Marshal(b, m, deterministic)
}
func (m *TaskDescriptionCP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDescriptionCP.Merge(m, src)
}
func (m *TaskDescriptionCP) XXX_Size() int {
	return xxx_messageInfo_TaskDescriptionCP.Size(m)
}
func (m *TaskDescriptionCP) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDescriptionCP.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDescriptionCP proto.InternalMessageInfo

func (m *TaskDescriptionCP) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TaskDescriptionCP) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *TaskDescriptionCP) GetLocations() []*P2PLocation {
	if m != nil {
		return m.Locations
	}
	return nil
}

type P2PLocation struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Addrs                []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PLocation) Reset()         { *m = P2PLocation{} }
func (m *P2PLocation) String() string { return proto.CompactTextString(m) }
func (*P2PLocation) ProtoMessage()    {}
func (*P2PLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{32}
}

func (m *P2PLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PLocation.Unmarshal(m, b)
}
func (m *P2PLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PLocation.Marshal(b, m, deterministic)
}
func (m *P2PLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PLocation.Merge(m, src)
}
func (m *P2PLocation) XXX_Size() int {
	return xxx_messageInfo_P2PLocation.Size(m)
}
func (m *P2PLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PLocation.DiscardUnknown(m)
}

var xxx_messageInfo_P2PLocation proto.InternalMessageInfo

func (m *P2PLocation) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *P2PLocation) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

//矿机收到任务请回复VoidResp
//msgid=0xe64f
type VoidResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidResponse) Reset()         { *m = VoidResponse{} }
func (m *VoidResponse) String() string { return proto.CompactTextString(m) }
func (*VoidResponse) ProtoMessage()    {}
func (*VoidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{33}
}

func (m *VoidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidResponse.Unmarshal(m, b)
}
func (m *VoidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidResponse.Marshal(b, m, deterministic)
}
func (m *VoidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidResponse.Merge(m, src)
}
func (m *VoidResponse) XXX_Size() int {
	return xxx_messageInfo_VoidResponse.Size(m)
}
func (m *VoidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoidResponse proto.InternalMessageInfo

//矿机重建完毕后向任务发起方SN返回结果
//msgid=0x16f3
type TaskOpResult struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RES                  int32    `protobuf:"varint,2,opt,name=RES,proto3" json:"RES,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskOpResult) Reset()         { *m = TaskOpResult{} }
func (m *TaskOpResult) String() string { return proto.CompactTextString(m) }
func (*TaskOpResult) ProtoMessage()    {}
func (*TaskOpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{34}
}

func (m *TaskOpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskOpResult.Unmarshal(m, b)
}
func (m *TaskOpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskOpResult.Marshal(b, m, deterministic)
}
func (m *TaskOpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskOpResult.Merge(m, src)
}
func (m *TaskOpResult) XXX_Size() int {
	return xxx_messageInfo_TaskOpResult.Size(m)
}
func (m *TaskOpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskOpResult.DiscardUnknown(m)
}

var xxx_messageInfo_TaskOpResult proto.InternalMessageInfo

func (m *TaskOpResult) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TaskOpResult) GetRES() int32 {
	if m != nil {
		return m.RES
	}
	return 0
}

//批量向任务发起方SN返回结果，注意所有结果必须是属于同一SN
//MessageID:1b31
type MultiTaskOpResult struct {
	Id                   [][]byte `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	RES                  []int32  `protobuf:"varint,2,rep,packed,name=RES,proto3" json:"RES,omitempty"`
	NodeID               int32    `protobuf:"varint,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,4,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	SrcNodeID            int32    `protobuf:"varint,5,opt,name=srcNodeID,proto3" json:"srcNodeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiTaskOpResult) Reset()         { *m = MultiTaskOpResult{} }
func (m *MultiTaskOpResult) String() string { return proto.CompactTextString(m) }
func (*MultiTaskOpResult) ProtoMessage()    {}
func (*MultiTaskOpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{35}
}

func (m *MultiTaskOpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiTaskOpResult.Unmarshal(m, b)
}
func (m *MultiTaskOpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiTaskOpResult.Marshal(b, m, deterministic)
}
func (m *MultiTaskOpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiTaskOpResult.Merge(m, src)
}
func (m *MultiTaskOpResult) XXX_Size() int {
	return xxx_messageInfo_MultiTaskOpResult.Size(m)
}
func (m *MultiTaskOpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiTaskOpResult.DiscardUnknown(m)
}

var xxx_messageInfo_MultiTaskOpResult proto.InternalMessageInfo

func (m *MultiTaskOpResult) GetId() [][]byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *MultiTaskOpResult) GetRES() []int32 {
	if m != nil {
		return m.RES
	}
	return nil
}

func (m *MultiTaskOpResult) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *MultiTaskOpResult) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *MultiTaskOpResult) GetSrcNodeID() int32 {
	if m != nil {
		return m.SrcNodeID
	}
	return 0
}

type BlockMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Vnf                  int32    `protobuf:"varint,2,opt,name=vnf,proto3" json:"vnf,omitempty"`
	Ar                   int32    `protobuf:"varint,3,opt,name=ar,proto3" json:"ar,omitempty"`
	SnID                 int32    `protobuf:"varint,4,opt,name=snID,proto3" json:"snID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMsg) Reset()         { *m = BlockMsg{} }
func (m *BlockMsg) String() string { return proto.CompactTextString(m) }
func (*BlockMsg) ProtoMessage()    {}
func (*BlockMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{36}
}

func (m *BlockMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMsg.Unmarshal(m, b)
}
func (m *BlockMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMsg.Marshal(b, m, deterministic)
}
func (m *BlockMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMsg.Merge(m, src)
}
func (m *BlockMsg) XXX_Size() int {
	return xxx_messageInfo_BlockMsg.Size(m)
}
func (m *BlockMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMsg proto.InternalMessageInfo

func (m *BlockMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BlockMsg) GetVnf() int32 {
	if m != nil {
		return m.Vnf
	}
	return 0
}

func (m *BlockMsg) GetAr() int32 {
	if m != nil {
		return m.Ar
	}
	return 0
}

func (m *BlockMsg) GetSnID() int32 {
	if m != nil {
		return m.SnID
	}
	return 0
}

type ShardMsg struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeID               int32    `protobuf:"varint,2,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Vhf                  []byte   `protobuf:"bytes,3,opt,name=vhf,proto3" json:"vhf,omitempty"`
	BlockID              int64    `protobuf:"varint,4,opt,name=blockID,proto3" json:"blockID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardMsg) Reset()         { *m = ShardMsg{} }
func (m *ShardMsg) String() string { return proto.CompactTextString(m) }
func (*ShardMsg) ProtoMessage()    {}
func (*ShardMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{37}
}

func (m *ShardMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardMsg.Unmarshal(m, b)
}
func (m *ShardMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardMsg.Marshal(b, m, deterministic)
}
func (m *ShardMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardMsg.Merge(m, src)
}
func (m *ShardMsg) XXX_Size() int {
	return xxx_messageInfo_ShardMsg.Size(m)
}
func (m *ShardMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ShardMsg proto.InternalMessageInfo

func (m *ShardMsg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShardMsg) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *ShardMsg) GetVhf() []byte {
	if m != nil {
		return m.Vhf
	}
	return nil
}

func (m *ShardMsg) GetBlockID() int64 {
	if m != nil {
		return m.BlockID
	}
	return 0
}

type CheckPointMsg struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPointMsg) Reset()         { *m = CheckPointMsg{} }
func (m *CheckPointMsg) String() string { return proto.CompactTextString(m) }
func (*CheckPointMsg) ProtoMessage()    {}
func (*CheckPointMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{38}
}

func (m *CheckPointMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPointMsg.Unmarshal(m, b)
}
func (m *CheckPointMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPointMsg.Marshal(b, m, deterministic)
}
func (m *CheckPointMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPointMsg.Merge(m, src)
}
func (m *CheckPointMsg) XXX_Size() int {
	return xxx_messageInfo_CheckPointMsg.Size(m)
}
func (m *CheckPointMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPointMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPointMsg proto.InternalMessageInfo

func (m *CheckPointMsg) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CheckPointMsg) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *CheckPointMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pbrebuilder.Empty")
	proto.RegisterType((*BoolMessage)(nil), "pbrebuilder.BoolMessage")
	proto.RegisterType((*StringMsg)(nil), "pbrebuilder.StringMsg")
	proto.RegisterType((*String2Msg)(nil), "pbrebuilder.String2Msg")
	proto.RegisterType((*Int32Msg)(nil), "pbrebuilder.Int32Msg")
	proto.RegisterType((*Int64Msg)(nil), "pbrebuilder.Int64Msg")
	proto.RegisterType((*NodeMsg)(nil), "pbrebuilder.NodeMsg")
	proto.RegisterMapType((map[string]int64)(nil), "pbrebuilder.NodeMsg.UspacesEntry")
	proto.RegisterType((*SuperNodeMsg)(nil), "pbrebuilder.SuperNodeMsg")
	proto.RegisterType((*NodeStatMsg)(nil), "pbrebuilder.NodeStatMsg")
	proto.RegisterType((*SpotCheckTaskMsg)(nil), "pbrebuilder.SpotCheckTaskMsg")
	proto.RegisterType((*SpotCheckListMsg)(nil), "pbrebuilder.SpotCheckListMsg")
	proto.RegisterType((*GetSpotCheckListResp)(nil), "pbrebuilder.GetSpotCheckListResp")
	proto.RegisterType((*NodesResp)(nil), "pbrebuilder.NodesResp")
	proto.RegisterType((*SuperNodesResp)(nil), "pbrebuilder.SuperNodesResp")
	proto.RegisterType((*IncrUsedSpaceReq)(nil), "pbrebuilder.IncrUsedSpaceReq")
	proto.RegisterType((*AllocNodesReq)(nil), "pbrebuilder.AllocNodesReq")
	proto.RegisterType((*GetNodesReq)(nil), "pbrebuilder.GetNodesReq")
	proto.RegisterType((*DNIReq)(nil), "pbrebuilder.DNIReq")
	proto.RegisterType((*UpdateTaskStatusReq)(nil), "pbrebuilder.UpdateTaskStatusReq")
	proto.RegisterType((*ShardCountMsg)(nil), "pbrebuilder.ShardCountMsg")
	proto.RegisterType((*GetInvalidNodesResp)(nil), "pbrebuilder.GetInvalidNodesResp")
	proto.RegisterType((*GetRebuildItemReq)(nil), "pbrebuilder.GetRebuildItemReq")
	proto.RegisterType((*GetRebuildItemResp)(nil), "pbrebuilder.GetRebuildItemResp")
	proto.RegisterType((*DownloadShardRequest)(nil), "pbrebuilder.DownloadShardRequest")
	proto.RegisterType((*DownloadShardResponse)(nil), "pbrebuilder.DownloadShardResponse")
	proto.RegisterType((*SignMessage)(nil), "pbrebuilder.SignMessage")
	proto.RegisterType((*UpdateUspaceMessage)(nil), "pbrebuilder.UpdateUspaceMessage")
	proto.RegisterType((*PunishMessage)(nil), "pbrebuilder.PunishMessage")
	proto.RegisterMapType((map[int32]int32)(nil), "pbrebuilder.PunishMessage.RuleEntry")
	proto.RegisterType((*RebuiltMessage)(nil), "pbrebuilder.RebuiltMessage")
	proto.RegisterType((*MultiTaskDescription)(nil), "pbrebuilder.MultiTaskDescription")
	proto.RegisterType((*TaskDescription)(nil), "pbrebuilder.TaskDescription")
	proto.RegisterType((*TaskDescriptionCP)(nil), "pbrebuilder.TaskDescriptionCP")
	proto.RegisterType((*P2PLocation)(nil), "pbrebuilder.P2PLocation")
	proto.RegisterType((*VoidResponse)(nil), "pbrebuilder.VoidResponse")
	proto.RegisterType((*TaskOpResult)(nil), "pbrebuilder.TaskOpResult")
	proto.RegisterType((*MultiTaskOpResult)(nil), "pbrebuilder.MultiTaskOpResult")
	proto.RegisterType((*BlockMsg)(nil), "pbrebuilder.BlockMsg")
	proto.RegisterType((*ShardMsg)(nil), "pbrebuilder.ShardMsg")
	proto.RegisterType((*CheckPointMsg)(nil), "pbrebuilder.CheckPointMsg")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 1677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5f, 0x6f, 0x1b, 0xc7,
	0x11, 0x0f, 0x49, 0x9d, 0x44, 0x0e, 0x29, 0x59, 0x3e, 0xcb, 0xe9, 0x85, 0x4d, 0x0d, 0x65, 0x13,
	0xb4, 0x42, 0x0a, 0x10, 0x0d, 0x53, 0x38, 0x71, 0x92, 0x97, 0xd8, 0x74, 0x65, 0x22, 0x91, 0x42,
	0x1c, 0x6d, 0x03, 0x7d, 0x68, 0xd1, 0xd5, 0xdd, 0x8a, 0x3c, 0xf8, 0x78, 0x7b, 0xde, 0xdd, 0xa3,
	0xc8, 0x97, 0xbe, 0xf4, 0xb9, 0x5f, 0xa0, 0xcf, 0xfd, 0x0c, 0x05, 0xfa, 0x61, 0xfa, 0xd6, 0x0f,
	0x52, 0xcc, 0xfe, 0xb9, 0x3f, 0x94, 0x1a, 0xa3, 0x45, 0xde, 0x76, 0x7e, 0x37, 0x3b, 0x33, 0x3b,
	0xf3, 0x9b, 0xd9, 0x25, 0xa1, 0xaf, 0xb6, 0x39, 0x93, 0xa3, 0x5c, 0x70, 0xc5, 0xfd, 0x7e, 0x7e,
	0x25, 0xd8, 0x55, 0x91, 0xa4, 0x31, 0x13, 0xe4, 0x00, 0xbc, 0xe7, 0xab, 0x5c, 0x6d, 0xc9, 0xc7,
	0xd0, 0x7f, 0xca, 0x79, 0x7a, 0xc1, 0xa4, 0xa4, 0x0b, 0xe6, 0x9f, 0x80, 0xb7, 0xa6, 0x69, 0xc1,
	0x82, 0xd6, 0x69, 0xeb, 0xac, 0x1b, 0x1a, 0x81, 0x7c, 0x04, 0xbd, 0xb9, 0x12, 0x49, 0xb6, 0xb8,
	0x90, 0x8b, 0xa6, 0x4a, 0xcf, 0xa9, 0x7c, 0x03, 0x60, 0x54, 0xc6, 0xa8, 0xf3, 0x3e, 0xec, 0xe7,
	0x54, 0xd0, 0xd5, 0x67, 0x56, 0xc9, 0x4a, 0x25, 0x3e, 0x0e, 0xda, 0x35, 0x7c, 0x4c, 0x4e, 0xa1,
	0x3b, 0xcd, 0xd4, 0xe7, 0xe3, 0x5b, 0xf6, 0x3d, 0x67, 0xdf, 0x68, 0x3c, 0xfe, 0xed, 0x2d, 0x8d,
	0x8e, 0xd3, 0xf8, 0xc7, 0x3e, 0x1c, 0x5c, 0xf2, 0x98, 0xa1, 0xc6, 0x11, 0xb4, 0x93, 0x89, 0x35,
	0xd0, 0x4e, 0x26, 0xe8, 0x37, 0xe3, 0x31, 0x9b, 0x4e, 0x9c, 0x5f, 0x23, 0xe9, 0x78, 0x8a, 0xab,
	0xef, 0xd8, 0x36, 0xe8, 0xd8, 0x78, 0xb4, 0x84, 0x1e, 0xf8, 0x4d, 0xc6, 0x44, 0xb0, 0x67, 0xce,
	0xa8, 0x05, 0xff, 0x43, 0xe8, 0xe5, 0x82, 0x5f, 0x27, 0xea, 0xdb, 0x28, 0x0a, 0x3c, 0xfd, 0xa5,
	0x02, 0xb4, 0x2d, 0xce, 0xd3, 0xe9, 0x24, 0xd8, 0xb7, 0xb6, 0xb4, 0xa4, 0x77, 0x71, 0x9e, 0xfe,
	0xa0, 0xed, 0x1d, 0xd8, 0x5d, 0x0e, 0x40, 0x4f, 0x6f, 0x0b, 0xae, 0x68, 0xd0, 0x35, 0x67, 0xd1,
	0x02, 0xa2, 0x34, 0x8e, 0x85, 0x0c, 0x7a, 0xa7, 0x1d, 0xf4, 0xaf, 0x05, 0xff, 0x18, 0x3a, 0xd1,
	0xec, 0x55, 0x00, 0xfa, 0x58, 0xb8, 0x44, 0x9f, 0x2b, 0xb6, 0xe2, 0x62, 0x1b, 0xf4, 0x35, 0x68,
	0x25, 0xf4, 0x79, 0x45, 0xb3, 0xf8, 0x26, 0x89, 0xd5, 0x32, 0x18, 0xe8, 0x4f, 0x15, 0xe0, 0x13,
	0x18, 0xac, 0xe8, 0x66, 0x42, 0x15, 0x9d, 0xe7, 0x34, 0x62, 0xc1, 0xa1, 0x76, 0xdd, 0xc0, 0xfc,
	0x4f, 0xe0, 0x90, 0x4a, 0x99, 0x2c, 0x32, 0x16, 0x1b, 0xa5, 0x23, 0xad, 0xd4, 0x04, 0xfd, 0x33,
	0xb8, 0x97, 0x0b, 0x1e, 0x17, 0x91, 0x4a, 0xd6, 0xcc, 0xe8, 0xdd, 0xd3, 0x7a, 0xbb, 0x30, 0x46,
	0x54, 0x48, 0x67, 0xeb, 0x58, 0xeb, 0x54, 0x00, 0x9e, 0xe3, 0x86, 0x25, 0x8b, 0xa5, 0x0a, 0xee,
	0x9f, 0xb6, 0xce, 0x5a, 0xa1, 0x95, 0x6c, 0xa5, 0x93, 0x38, 0xf0, 0x4b, 0x2e, 0x24, 0x31, 0xa2,
	0x82, 0xa5, 0x74, 0x1b, 0x3c, 0x30, 0xa8, 0x16, 0xd0, 0x86, 0x54, 0x54, 0x15, 0x32, 0x38, 0x31,
	0xb9, 0x30, 0x12, 0x7a, 0x56, 0xc9, 0x8a, 0x49, 0x45, 0x57, 0x79, 0xf0, 0xd0, 0x78, 0x2e, 0x01,
	0x3f, 0x80, 0x83, 0x35, 0x13, 0x32, 0xe1, 0x59, 0xf0, 0xbe, 0xde, 0xe6, 0x44, 0xff, 0x11, 0x80,
	0xed, 0x97, 0x24, 0x5b, 0x04, 0x3f, 0xd3, 0x1f, 0x6b, 0x08, 0xda, 0x15, 0x8c, 0xa6, 0xe6, 0x44,
	0x81, 0xb1, 0x5b, 0x02, 0xc8, 0x40, 0xb5, 0x09, 0x3e, 0xd0, 0x70, 0x5b, 0x6d, 0x50, 0x16, 0x9b,
	0x60, 0x68, 0x64, 0xb1, 0xc1, 0x5a, 0xb2, 0x8d, 0x0a, 0x7e, 0xae, 0xf9, 0x80, 0x4b, 0xff, 0x6b,
	0x38, 0x28, 0x24, 0xee, 0x95, 0xc1, 0x87, 0xa7, 0x9d, 0xb3, 0xfe, 0xf8, 0xa3, 0x51, 0xad, 0x63,
	0x47, 0x96, 0xda, 0xa3, 0x57, 0x46, 0xe7, 0x79, 0xa6, 0xc4, 0x36, 0x74, 0x3b, 0x86, 0x5f, 0xc1,
	0xa0, 0xfe, 0x01, 0xcd, 0xbf, 0x61, 0x5b, 0xdb, 0x7d, 0xb8, 0xac, 0x9a, 0xa6, 0x5d, 0x6b, 0x9a,
	0xaf, 0xda, 0x5f, 0xb6, 0xc8, 0x9f, 0x61, 0x30, 0x2f, 0x72, 0x26, 0x7e, 0xaa, 0xe6, 0x09, 0xe0,
	0x20, 0x17, 0xc9, 0x1a, 0x3f, 0x98, 0xf6, 0x71, 0x62, 0x45, 0x6b, 0xaf, 0x46, 0x6b, 0xf2, 0xaf,
	0x16, 0xf4, 0xd1, 0xf7, 0x5c, 0x51, 0x85, 0xfe, 0x09, 0x0c, 0xa8, 0x66, 0xce, 0x45, 0x92, 0x31,
	0x21, 0x6d, 0x97, 0x37, 0x30, 0xff, 0x14, 0xfa, 0x8a, 0x2b, 0x9a, 0x5a, 0x15, 0x73, 0xa6, 0x3a,
	0xe4, 0x0f, 0xa1, 0xbb, 0xa2, 0x9b, 0x97, 0x88, 0xe8, 0xf8, 0x3a, 0x61, 0x29, 0xd7, 0xc9, 0x6d,
	0x14, 0xf6, 0x9a, 0xe4, 0x36, 0x5a, 0x0d, 0x72, 0x1b, 0x3d, 0x6f, 0x97, 0xdc, 0x46, 0xd3, 0x92,
	0xdb, 0xe8, 0xec, 0x57, 0xe4, 0xd6, 0x00, 0xf9, 0x13, 0x1c, 0xcf, 0x73, 0xae, 0x9e, 0x2d, 0x59,
	0xf4, 0xe6, 0x25, 0x95, 0x6f, 0xfe, 0x97, 0x1c, 0xfb, 0xb0, 0x87, 0x49, 0xb2, 0x19, 0xd6, 0x6b,
	0xac, 0xed, 0xfa, 0x72, 0x6a, 0x73, 0x8b, 0x4b, 0xf2, 0x97, 0x56, 0xcd, 0xc5, 0xf7, 0x89, 0x54,
	0x76, 0x06, 0x2b, 0x2a, 0xdf, 0x4c, 0x27, 0x6e, 0x06, 0x1b, 0xc9, 0x7f, 0x02, 0x5d, 0x5c, 0xa1,
	0x5a, 0xd0, 0xd6, 0x44, 0xfb, 0x45, 0x83, 0x68, 0xbb, 0xb1, 0x86, 0xa5, 0x7a, 0xb3, 0x95, 0x3a,
	0x3b, 0xad, 0x44, 0xfe, 0x00, 0x27, 0xe7, 0x4c, 0x35, 0xe2, 0x08, 0x99, 0xcc, 0xfd, 0xe7, 0x70,
	0x24, 0xeb, 0x20, 0x56, 0xf4, 0x47, 0xdc, 0xda, 0xf8, 0xc3, 0x9d, 0x4d, 0xe4, 0x0b, 0xe8, 0x21,
	0x4b, 0xa4, 0xb6, 0xf9, 0x29, 0x78, 0x98, 0x21, 0x67, 0xea, 0xe4, 0xae, 0x56, 0x09, 0x8d, 0x0a,
	0xf9, 0x0e, 0x8e, 0x4a, 0x7e, 0x9b, 0xdd, 0x4f, 0x00, 0x64, 0x89, 0x58, 0x13, 0x1f, 0x34, 0xa3,
	0xa9, 0x35, 0x44, 0x58, 0x53, 0x26, 0x8f, 0xe1, 0x78, 0x9a, 0x45, 0xe2, 0x95, 0x1b, 0x5d, 0x21,
	0x7b, 0xab, 0x8b, 0x19, 0x97, 0xc5, 0x8c, 0xb1, 0x68, 0x49, 0x16, 0x09, 0xcb, 0x4a, 0xbd, 0x26,
	0xe7, 0x70, 0xf8, 0x6d, 0x9a, 0xf2, 0xc8, 0x06, 0xf1, 0x16, 0xc7, 0x8b, 0x5c, 0x52, 0x11, 0x3f,
	0xe3, 0x45, 0xa6, 0xec, 0xe6, 0x1a, 0x82, 0xe5, 0x63, 0x42, 0x4c, 0x27, 0x52, 0x17, 0xc9, 0x0b,
	0xad, 0x44, 0x7e, 0x05, 0xfd, 0x73, 0xa6, 0x4a, 0x33, 0x01, 0x1c, 0x18, 0xaa, 0x98, 0x73, 0x78,
	0xa1, 0x13, 0xc9, 0x08, 0xf6, 0x27, 0x97, 0xd3, 0xbb, 0xe2, 0x3b, 0x01, 0x4f, 0x3b, 0xd2, 0x01,
	0x0e, 0x42, 0x23, 0x90, 0x73, 0x78, 0xf0, 0x2a, 0x8f, 0xa9, 0x62, 0x58, 0xf7, 0xb9, 0x9e, 0x9d,
	0xcd, 0xcd, 0x3d, 0xbd, 0xf9, 0x14, 0xfa, 0x49, 0xa6, 0xe7, 0x30, 0xc6, 0xa0, 0x4d, 0x78, 0x61,
	0x1d, 0x22, 0x9f, 0xc1, 0xe1, 0xbc, 0x3c, 0xc7, 0x5d, 0x64, 0xc7, 0x7b, 0x2c, 0x53, 0x36, 0x3d,
	0xb8, 0x24, 0x73, 0x78, 0x70, 0xce, 0xd4, 0xb4, 0x32, 0x62, 0xea, 0xf4, 0x0d, 0xf4, 0xab, 0x8c,
	0xb8, 0x42, 0x0d, 0x9b, 0x85, 0xaa, 0x7b, 0x0a, 0xeb, 0xea, 0xe4, 0xf7, 0x70, 0xff, 0x9c, 0xa9,
	0xd0, 0xa8, 0x4e, 0x15, 0x5b, 0xd9, 0x7c, 0xad, 0x70, 0x40, 0x4c, 0x5d, 0x40, 0x4e, 0xc4, 0xac,
	0x24, 0x59, 0xcc, 0x36, 0x6e, 0x40, 0x6a, 0x01, 0x51, 0x55, 0x9b, 0x21, 0x46, 0x20, 0xaf, 0xc1,
	0xdf, 0x35, 0x2d, 0x73, 0xff, 0x0c, 0xf6, 0x30, 0xf9, 0xda, 0xf0, 0x7f, 0xe3, 0xa4, 0xd6, 0xd0,
	0x77, 0x15, 0x46, 0x6a, 0x8a, 0x3b, 0x08, 0xad, 0x44, 0xce, 0xe0, 0x64, 0xc2, 0x6f, 0xb2, 0x94,
	0xd3, 0x58, 0x1f, 0x2c, 0x64, 0x6f, 0x0b, 0x26, 0x15, 0x66, 0xec, 0xf5, 0x8b, 0xdf, 0x69, 0xc3,
	0x83, 0x10, 0x97, 0xe4, 0xd7, 0xf0, 0x70, 0x47, 0x53, 0xe6, 0x3c, 0x93, 0x0c, 0xc9, 0x17, 0x53,
	0x45, 0xad, 0xae, 0x5e, 0x13, 0x0a, 0xfd, 0x79, 0xb2, 0xc8, 0xdc, 0x23, 0xef, 0x14, 0xfa, 0x34,
	0x8a, 0x30, 0x49, 0x97, 0x74, 0xe5, 0xde, 0x71, 0x75, 0xa8, 0x34, 0xd2, 0xae, 0x8c, 0x60, 0xf3,
	0xe3, 0x74, 0xa4, 0xaa, 0x10, 0xcc, 0xce, 0xa3, 0x0a, 0x20, 0xcc, 0xb1, 0xc7, 0x5c, 0x43, 0xce,
	0x55, 0x35, 0xd7, 0x4c, 0xb6, 0xdd, 0x5c, 0x7b, 0x04, 0x70, 0x2d, 0xf8, 0xea, 0xb2, 0x9a, 0x79,
	0x5e, 0x58, 0x43, 0x70, 0x9f, 0xb9, 0xda, 0x6c, 0xde, 0xad, 0x44, 0xfe, 0xdd, 0x82, 0xc3, 0x59,
	0x91, 0x25, 0x72, 0xf9, 0x2e, 0x0f, 0x3e, 0xec, 0xe1, 0xeb, 0xd7, 0xda, 0xd6, 0x6b, 0xf4, 0x9a,
	0x31, 0x16, 0x1b, 0x03, 0xda, 0x72, 0x37, 0xac, 0x21, 0x58, 0x6c, 0x9d, 0x03, 0x3d, 0x5b, 0xbd,
	0xd0, 0x08, 0xfe, 0x97, 0xb0, 0x27, 0x8a, 0x94, 0xe9, 0x4b, 0xab, 0x3f, 0xfe, 0xa4, 0x51, 0xd6,
	0x46, 0x2c, 0xa3, 0xb0, 0x48, 0x99, 0xb9, 0x98, 0xf5, 0x8e, 0xe1, 0x17, 0xd0, 0x2b, 0xa1, 0xfa,
	0x95, 0xec, 0xdd, 0x71, 0x25, 0x7b, 0xf5, 0x2b, 0xf9, 0x0c, 0x8e, 0x0c, 0xb9, 0xd4, 0x3b, 0x8e,
	0x49, 0xfe, 0xd6, 0x82, 0x93, 0x8b, 0x22, 0x55, 0x09, 0x76, 0xed, 0x84, 0xc9, 0x48, 0x24, 0xb9,
	0xc2, 0xe7, 0xcb, 0xd0, 0x8c, 0xf9, 0x14, 0xc7, 0x7c, 0x4b, 0x93, 0xac, 0x94, 0x91, 0x00, 0x6c,
	0x93, 0x27, 0x82, 0xc5, 0x2f, 0x93, 0x95, 0x7b, 0x11, 0xd4, 0x21, 0x5d, 0x6c, 0x11, 0xd9, 0xf2,
	0x74, 0xcc, 0x03, 0xb2, 0x04, 0xfc, 0x5f, 0xc2, 0x51, 0x4d, 0xf9, 0x9c, 0xe6, 0x36, 0x61, 0x3b,
	0x28, 0xf9, 0x67, 0x0b, 0xee, 0xed, 0xc6, 0x55, 0xcd, 0x93, 0x81, 0x1b, 0x46, 0x4b, 0x2a, 0x97,
	0xae, 0x13, 0x8c, 0xe0, 0x3f, 0x86, 0x5e, 0xca, 0x23, 0x8a, 0x3b, 0x64, 0xd0, 0xd1, 0x89, 0x0f,
	0x9a, 0x89, 0x1f, 0xcf, 0xbe, 0xb7, 0x0a, 0x61, 0xa5, 0xea, 0x7f, 0x0a, 0xc7, 0x39, 0x15, 0x89,
	0xda, 0x56, 0x73, 0xc1, 0xc6, 0x76, 0x0b, 0x37, 0x0f, 0xb8, 0x88, 0xaf, 0x99, 0x98, 0xc6, 0xfa,
	0x66, 0xf7, 0xc2, 0x0a, 0x20, 0x37, 0x70, 0x7f, 0x27, 0xf4, 0x67, 0xb3, 0x5b, 0xc1, 0x0f, 0xa1,
	0x8b, 0xbd, 0xf1, 0x82, 0xca, 0xa5, 0xed, 0x95, 0x52, 0xfe, 0x7f, 0x8f, 0x40, 0xbe, 0x86, 0x7e,
	0xed, 0x4b, 0x59, 0x78, 0x37, 0x83, 0xad, 0x54, 0xbd, 0xa5, 0xda, 0xf5, 0xb7, 0xd4, 0x11, 0x0c,
	0x5e, 0xf3, 0xa4, 0x9c, 0x06, 0xe4, 0x37, 0x30, 0xc0, 0x53, 0xfc, 0x90, 0x87, 0x4c, 0x16, 0xa9,
	0xba, 0x75, 0x80, 0x63, 0xe8, 0x84, 0xcf, 0xe7, 0x96, 0x80, 0xb8, 0x24, 0x7f, 0x6d, 0xc1, 0xfd,
	0x92, 0x50, 0xb7, 0xf6, 0x75, 0x76, 0xf7, 0x75, 0xec, 0x3e, 0x8c, 0xb3, 0x41, 0x17, 0x2b, 0xed,
	0x72, 0x6d, 0xef, 0x1d, 0x5c, 0xf3, 0x76, 0xb8, 0x46, 0x66, 0xd0, 0x7d, 0x9a, 0xf2, 0xa8, 0x7c,
	0x35, 0xc5, 0xf6, 0x3d, 0x68, 0xa3, 0x58, 0x67, 0xd7, 0x2e, 0xfa, 0x75, 0x76, 0x8d, 0x1a, 0x54,
	0xd8, 0x08, 0xda, 0x54, 0xe0, 0x14, 0x90, 0xd9, 0x74, 0x62, 0x39, 0xa0, 0xd7, 0xe4, 0x8f, 0xd0,
	0xd5, 0x2c, 0xb8, 0xcb, 0x62, 0xf3, 0x1d, 0x56, 0x4d, 0x13, 0xf4, 0xb4, 0xbc, 0xd6, 0x86, 0x07,
	0x21, 0x2e, 0xf1, 0x22, 0xb9, 0xc2, 0xb8, 0xac, 0xf1, 0x4e, 0xe8, 0x44, 0x32, 0x87, 0x43, 0xfd,
	0x6c, 0x99, 0xf1, 0xa4, 0xba, 0xff, 0x76, 0xef, 0x5f, 0x45, 0x85, 0xbb, 0x01, 0x8d, 0xf0, 0xe3,
	0x8f, 0xab, 0xf1, 0xdf, 0x5b, 0xd0, 0x0b, 0x1d, 0x75, 0xfc, 0x0b, 0xb8, 0x57, 0xdd, 0x3f, 0x58,
	0x28, 0xe9, 0x3f, 0x6c, 0x70, 0xcb, 0xfd, 0x9a, 0x1e, 0x36, 0x7f, 0x44, 0xdc, 0x35, 0x29, 0xc8,
	0x7b, 0xfe, 0x0b, 0x38, 0xde, 0xbd, 0xfa, 0xfd, 0x47, 0x77, 0x6f, 0x74, 0x8c, 0x18, 0xfa, 0x8d,
	0xef, 0xe6, 0xcf, 0x84, 0xf7, 0x9e, 0x3e, 0x81, 0x8f, 0x13, 0x3e, 0xda, 0x72, 0xa5, 0x68, 0xb4,
	0xa4, 0x49, 0x36, 0xc2, 0xfc, 0xad, 0x16, 0x2b, 0x35, 0xaa, 0x74, 0xf3, 0xab, 0xa7, 0x47, 0xe5,
	0x51, 0x66, 0x82, 0x2b, 0xfe, 0xa2, 0x35, 0x6b, 0x5d, 0xed, 0xeb, 0xbf, 0x29, 0x3e, 0xff, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x8c, 0x4c, 0xbb, 0xb5, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RebuilderClient is the client API for Rebuilder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RebuilderClient interface {
	GetRebuildTasks(ctx context.Context, in *Int32Msg, opts ...grpc.CallOption) (*MultiTaskDescription, error)
	UpdateTaskStatus(ctx context.Context, in *MultiTaskOpResult, opts ...grpc.CallOption) (*Empty, error)
}

type rebuilderClient struct {
	cc *grpc.ClientConn
}

func NewRebuilderClient(cc *grpc.ClientConn) RebuilderClient {
	return &rebuilderClient{cc}
}

func (c *rebuilderClient) GetRebuildTasks(ctx context.Context, in *Int32Msg, opts ...grpc.CallOption) (*MultiTaskDescription, error) {
	out := new(MultiTaskDescription)
	err := c.cc.Invoke(ctx, "/pbrebuilder.Rebuilder/GetRebuildTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rebuilderClient) UpdateTaskStatus(ctx context.Context, in *MultiTaskOpResult, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/pbrebuilder.Rebuilder/UpdateTaskStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RebuilderServer is the server API for Rebuilder service.
type RebuilderServer interface {
	GetRebuildTasks(context.Context, *Int32Msg) (*MultiTaskDescription, error)
	UpdateTaskStatus(context.Context, *MultiTaskOpResult) (*Empty, error)
}

// UnimplementedRebuilderServer can be embedded to have forward compatible implementations.
type UnimplementedRebuilderServer struct {
}

func (*UnimplementedRebuilderServer) GetRebuildTasks(ctx context.Context, req *Int32Msg) (*MultiTaskDescription, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRebuildTasks not implemented")
}
func (*UnimplementedRebuilderServer) UpdateTaskStatus(ctx context.Context, req *MultiTaskOpResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskStatus not implemented")
}

func RegisterRebuilderServer(s *grpc.Server, srv RebuilderServer) {
	s.RegisterService(&_Rebuilder_serviceDesc, srv)
}

func _Rebuilder_GetRebuildTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int32Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RebuilderServer).GetRebuildTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbrebuilder.Rebuilder/GetRebuildTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RebuilderServer).GetRebuildTasks(ctx, req.(*Int32Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rebuilder_UpdateTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiTaskOpResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RebuilderServer).UpdateTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbrebuilder.Rebuilder/UpdateTaskStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RebuilderServer).UpdateTaskStatus(ctx, req.(*MultiTaskOpResult))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rebuilder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbrebuilder.Rebuilder",
	HandlerType: (*RebuilderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRebuildTasks",
			Handler:    _Rebuilder_GetRebuildTasks_Handler,
		},
		{
			MethodName: "UpdateTaskStatus",
			Handler:    _Rebuilder_UpdateTaskStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
